services:

  kitchen:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config
        port: 8070
    ports:
      - "8070:8070"

  kitchen-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-1
        port: 8071
    ports:
      - "8071:8071"

  kitchen-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config-2
        port: 8072
    ports:
      - "8072:8072"

networks:
  default:
    name: restaurant
    external: true